spring.application.name=echobeacon

spring.mvc.hiddenmethod.filter.enabled=true

# Disable Spring Security auto-configuration
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

# MQTT configuration
mqtt.brokerUrl=tcp://broker.hivemq.com:1883
mqtt.clientId=echobeacon-mvc
mqtt.topic=fiap/iot/echobeacon/comando